apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "{{ .Values.service.backend_protocol }}"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .Values.service.ssl_cert }}"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "{{ .Values.service.ssl_port }}"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  selector:
    app: {{ .Release.Name }}-app
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.http_port }}
    targetPort: {{ .Values.service.http_target_port }}
  - name: https
    port: {{ .Values.service.https_port }}
    targetPort: {{ .Values.service.https_target_port }}